title: "InterXAI: Human-Centered Explainable AI and Intertextual Critique"
baseurl: "/interxai.github.io"
url: "https://bfiliks.github.io"
theme: minima

markdown: kramdown

permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag
