title: "InterXAI: Human-Centered Explainable AI and Intertextual Critique"
description: A platform for exploring human-centered Explainable AI and intertextual critique.

# Default values (for GitHub Pages)
url: "https://bfiliks.github.io"
baseurl: "/interxai.github.io"

# Netlify overrides these via environment variables if set
theme: minima
permalink: pretty
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: default

collections:
  case_studies:
    output: true
