title: "InterXAI: Human-Centered Explainable AI and Intertextual Critique"
description: A platform for exploring human-centered Explainable AI and intertextual critique.

# Netlify/GitHub Pages dual support
url: "${URL}"        # Will be replaced by Netlify env variable
baseurl: "${BASEURL}" # Will be replaced by Netlify env variable

theme: minima
permalink: pretty
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: default

collections:
  case_studies:
    output: true
