title: InterXAI Blog Demo
baseurl: "/interxai.github.io"
url: "https://bfiliks.github.io"
theme: minima

markdown: kramdown

# Optional GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
