title: InterXAI
email: felixo2@illinois.edu
description: Human-Centered Explainable AI meets Intertextuality
baseurl: "/interxai.github.io"
url: "https://bfiliks.github.io"

collections:
  posts:
    output: true
