title: "InterXAI: Human-Centered Explainable AI and Intertextual Critique"
description: "A platform for exploring human-centered Explainable AI and intertextual critique."

url: "https://bfiliks.github.io"
baseurl: "/interxai.github.io"

theme: minima
permalink: pretty
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: default

collections:
  case_studies:
    output: true
