source 'https://rubygems.org'

gem 'jekyll', '~> 4.3.4'
gem 'webrick', '~> 1.8'
gem 'jekyll-sass-converter', '~> 3.1'
gem 'sass-embedded', '~> 1.89'
gem 'kramdown-parser-gfm'
gem 'listen', '~> 3.9'
gem 'base64'
gem 'logger'
gem 'csv'
gem 'minima', '~> 2.5'
