[build]
  command = "bundle exec jekyll build --config _config_netlify.yml"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.2.2"

[context.production.environment]
  JEKYLL_ENV = "production"
